version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - baleenstudio
  - Borland
  - Brumme
  - CLSID
  - COMCTL
  - Edsger
  - Hanselman
  - Hyrum
  - jgraph
  - liba
  - libb
  - libbase
  - libfoo
  - libuser
  - LINQ
  - Makefiles
  - monomorphization
  - MSVC
  - MSVCR
  - MSVCRT
  - muxer
  - Pratschner
  - prezto
  - pyenv
  - runtimeconfig
  - SONAME
  - Strahl
  - unobtanium
  - vtable
  - XCOPY
  - Zenn
  - zprezto
ignoreWords: []
import: []
