version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Addy
  - aicoding
  - Bacchelli
  - baleenstudio
  - Birgitta
  - Böckeler
  - Borland
  - Brumme
  - CLSID
  - codereview
  - Collina
  - COMCTL
  - Czerwonka
  - Edsger
  - evals
  - Gloaguen
  - Greiler
  - Hanselman
  - Hyrum
  - ICSE
  - jgraph
  - liba
  - libb
  - libbase
  - libfoo
  - libuser
  - LINQ
  - Makefiles
  - Manshreck
  - martinfowler
  - Matteo
  - monomorphization
  - MSVC
  - MSVCR
  - MSVCRT
  - muxer
  - Naur
  - nielstron
  - Osmani
  - pamelafox
  - Pichai
  - Pratschner
  - prezto
  - pyenv
  - runtimeconfig
  - SONAME
  - Strahl
  - Thoughtworks
  - unobtanium
  - Upsun
  - Vogels
  - vtable
  - Willison
  - XCOPY
  - Zenn
  - zprezto
ignoreWords: []
import: []
